[@b.head/]
  [@b.grid items=clazzes var="clazz"]
    [@b.row]
      [@b.col title="序号" width="4%" property="crn"/]
      [@b.col title="任课教师" width="7%"]
        [#list clazz.teachers as t]${t.name}[#sep],[/#list]
      [/@]
      [@b.col title="课程名称" property="course.name"/]
      [@b.col title="开课院系" property="teachDepart.name" width="10%"/]
      [@b.col title="学分" property="course.defaultCredits" width="4%"/]
      [@b.col title="教学班" width="13%"]
        <div style="max-width: 200px;" class="text-ellipsis" title="${clazz.clazzName}">${clazz.clazzName}</div>
      [/@]
      [@b.col title="课程类别" property="courseType.name" width="15%"/]
      [@b.col title="人数" property="enrollment.stdCount" width="4%"/]
      [@b.col title="上课时间" width="9%"]
        ${activities[clazz.id?string]!}
      [/@]
      [@b.col title="上课地点" width="9%"]
        ${rooms[clazz.id?string]!}
      [/@]
      [@b.col title="操作" width="7%"]
        [#if taskIds?seq_contains(clazz.id)]
          [@b.a href="!edit?clazz.id=${clazz.id}" target="_blank"]填写[/@]
          [@b.a href="!report?clazz.id=${clazz.id}" target="_blank"]查看[/@]
        [#else]
          [@b.a href="!edit?clazz.id=${clazz.id}" target="_blank"]填写[/@]
        [/#if]
      [/@]
    [/@]
  [/@]
 [#list 1..5 as i]<br>[/#list]
[@b.foot/]
